"""document processing lifecycle

Revision ID: 75e4f9ae6768
Revises: 5abfae067775
Create Date: 2026-09-16 17:39:18.226826
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "75e4f9ae6768"
down_revision: str | None = "5abfae067775"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("attempts", sa.Integer(), server_default="0", nullable=False))
        batch_op.add_column(sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("error", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("page_count", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("parser_version", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f("ix_documents_status"), ["status"], unique=False)

    # ### end Alembic commands ###
    op.execute("UPDATE documents SET status = 'queued' WHERE status = 'uploaded'")


def downgrade() -> None:
    op.execute("UPDATE documents SET status = 'uploaded'")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_status"))
        batch_op.drop_column("parsed_at")
        batch_op.drop_column("parser_version")
        batch_op.drop_column("page_count")
        batch_op.drop_column("error")
        batch_op.drop_column("locked_at")
        batch_op.drop_column("attempts")

    # ### end Alembic commands ###
